package com.cmig.future.csportal.module.villager.integral.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xl_integral_detail")
public class IntegralDetail extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private Long totalScores;

      private Long changeScores;

      private String changeDescribe;

      private String userId;

      private Date changeDate;

      private String scoresCode;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTotalScores(Long totalScores){
         this.totalScores = totalScores;
     }

     public Long getTotalScores(){
         return totalScores;
     }

     public void setChangeScores(Long changeScores){
         this.changeScores = changeScores;
     }

     public Long getChangeScores(){
         return changeScores;
     }

     public void setChangeDescribe(String changeDescribe){
         this.changeDescribe = changeDescribe;
     }

     public String getChangeDescribe(){
         return changeDescribe;
     }

     public void setUserId(String userId){
         this.userId = userId;
     }

     public String getUserId(){
         return userId;
     }

     public void setChangeDate(Date changeDate){
         this.changeDate = changeDate;
     }

     public Date getChangeDate(){
         return changeDate;
     }

     public void setScoresCode(String scoresCode){
         this.scoresCode = scoresCode;
     }

     public String getScoresCode(){
         return scoresCode;
     }

     }
