package com.cmig.future.csportal.module.adv.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;

import javax.persistence.Id;
import javax.persistence.Table;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "csp_app_adv")
public class AppAdv extends BaseDTO {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3721453006593126053L;

	/**
	 * 
	 */


	@Id
     @GeneratedValue
      private Long advId;

      private String title;//* 广告名称

      private String description;

      private String urlType;

      private String url;//*地址

      private String pic;//*广告图

      private Long advType;//*广告位置  1单图 2轮播 3左一右二 4单行三图

      private Long status;//广告状态 1待审核 2审核失败 3待上线 4已上线 5已下线

      private Long advRank;//ADV_RANK排序大的在前

      private Long approvalBy;//批准用户

      private String approvalComment = "";//批准注释

      private Long advBegin;//*上线时间

      private Long advEnd;//*下线时间
      
      private Long isCas;//*是否单点登录
      
      private String groupIdentifying;//分组辨识
      
      private String descriptionOne;//第一行文字
      
      private String descriptionTwo;//第二行文字
      
      public String getDescriptionOne() {
		return descriptionOne;
	}

	public void setDescriptionOne(String descriptionOne) {
		this.descriptionOne = descriptionOne;
	}

	public String getDescriptionTwo() {
		return descriptionTwo;
	}

	public void setDescriptionTwo(String descriptionTwo) {
		this.descriptionTwo = descriptionTwo;
	}

	public String getGroupIdentifying() {
		return groupIdentifying;
	}

	public void setGroupIdentifying(String groupIdentifying) {
		this.groupIdentifying = groupIdentifying;
	}

     public Long getIsCas() {
		return isCas;
	}

	public void setIsCas(Long isCas) {
		this.isCas = isCas;
	}

	public void setAdvId(Long advId){
         this.advId = advId;
     }

     public Long getAdvId(){
         return advId;
     }

     public void setTitle(String title){
         this.title = title;
     }

     public String getTitle(){
         return title;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setUrlType(String urlType){
         this.urlType = urlType;
     }

     public String getUrlType(){
         return urlType;
     }

     public void setUrl(String url){
         this.url = url;
     }

     public String getUrl(){
         return url;
     }

     public void setPic(String pic){
         this.pic = pic;
     }

     public String getPic(){
         return pic;
     }

     public void setAdvType(Long advType){
         this.advType = advType;
     }

     public Long getAdvType(){
         return advType;
     }

     public void setStatus(Long status){
         this.status = status;
     }

     public Long getStatus(){
         return status;
     }

     public void setAdvRank(Long advRank){
         this.advRank = advRank;
     }

     public Long getAdvRank(){
         return advRank;
     }

     public void setApprovalBy(Long approvalBy){
         this.approvalBy = approvalBy;
     }

     public Long getApprovalBy(){
         return approvalBy;
     }

     public void setApprovalComment(String approvalComment){
         this.approvalComment = approvalComment;
     }

     public String getApprovalComment(){
         return approvalComment;
     }

     public void setAdvBegin(Long advBegin){
         this.advBegin = advBegin;
     }

     public Long getAdvBegin(){
         return advBegin;
     }

     public void setAdvEnd(Long advEnd){
         this.advEnd = advEnd;
     }

     public Long getAdvEnd(){
         return advEnd;
     }

	@Override
	public String toString() {
		return "{\"AppAdv\":{\"advId\":\"" + advId + "\",\"title\":\"" + title + "\",\"description\":\"" + description
				+ "\",\"urlType\":\"" + urlType + "\",\"url\":\"" + url + "\",\"pic\":\"" + pic + "\",\"advType\":\""
				+ advType + "\",\"status\":\"" + status + "\",\"advRank\":\"" + advRank + "\",\"approvalBy\":\""
				+ approvalBy + "\",\"approvalComment\":\"" + approvalComment + "\",\"advBegin\":\"" + advBegin
				+ "\",\"advEnd\":\"" + advEnd + "\",\"isCas\":\"" + isCas + "\",\"groupIdentifying\":\""
				+ groupIdentifying + "\",\"descriptionOne\":\"" + descriptionOne + "\",\"descriptionTwo\":\""
				+ descriptionTwo + "\"}}";
	}

     }


