package com.cmig.future.csportal.module.sys.openinfo.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "csp_ljh_open_app_info")
public class OpenAppInfo extends BaseDTO {

    @Id
    private String id;

    private String delFlag;

    private Long createdBy;

    private Date creationDate;

    private Long lastUpdatedBy;

    private Date lastUpdateDate;

    private Long lastUpdateLogin;

    private String officialId;

    private String paymentConfigId;

    @Transient
    private String pingAppName;

    @NotEmpty
    private String appKey;

    @NotEmpty
    private String appSecret;

    @Length(min=0, max=100, message="授权回调页的路径长度必须介于 0 和 100 之间")
    private String notifyUrl;

    @Length(min=0, max=100, message="应用服务器IP地址长度必须介于 0 和 100 之间")
    private String serverIp;

    @NotEmpty
    private String appName;

    @NotEmpty
    private String appStatus;


    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public String getDelFlag() {
        return delFlag;
    }

    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    public Long getCreatedBy() {
        return createdBy;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateLogin(Long lastUpdateLogin) {
        this.lastUpdateLogin = lastUpdateLogin;
    }

    public Long getLastUpdateLogin() {
        return lastUpdateLogin;
    }

    public void setOfficialId(String officialId) {
        this.officialId = officialId;
    }

    public String getOfficialId() {
        return officialId;
    }

    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    public String getAppKey() {
        return appKey;
    }

    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    public String getAppSecret() {
        return appSecret;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    public String getServerIp() {
        return serverIp;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus;
    }

    public String getAppStatus() {
        return appStatus;
    }

    public String getPaymentConfigId() {
        return paymentConfigId;
    }

    public void setPaymentConfigId(String paymentConfigId) {
        this.paymentConfigId = paymentConfigId;
    }

    public String getPingAppName() {
        return pingAppName;
    }

    public void setPingAppName(String pingAppName) {
        this.pingAppName = pingAppName;
    }
}
