package com.cmig.future.csportal.module.properties.mgtuser.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_mgt_user_syn")
public class MgtUserSyn extends BaseDTO {
     @Id
      private String id;

      private String userId;

      private String sourceSystem;

      private String sourceSystemId;

      private Long createdBy;

      private Date creationDate;

      private Long lastUpdatedBy;

      private Date lastUpdateDate;

      private Long lastUpdateLogin;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setUserId(String userId){
         this.userId = userId;
     }

     public String getUserId(){
         return userId;
     }

     public void setSourceSystem(String sourceSystem){
         this.sourceSystem = sourceSystem;
     }

     public String getSourceSystem(){
         return sourceSystem;
     }

     public void setSourceSystemId(String sourceSystemId){
         this.sourceSystemId = sourceSystemId;
     }

     public String getSourceSystemId(){
         return sourceSystemId;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

     public void setLastUpdateDate(Date lastUpdateDate){
         this.lastUpdateDate = lastUpdateDate;
     }

     public Date getLastUpdateDate(){
         return lastUpdateDate;
     }

     public void setLastUpdateLogin(Long lastUpdateLogin){
         this.lastUpdateLogin = lastUpdateLogin;
     }

     public Long getLastUpdateLogin(){
         return lastUpdateLogin;
     }

     }
