package com.cmig.future.csportal.module.properties.mgtuser.dto;

/**Auto Generated By Hap Code Generator**/
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_mgt_user_community")
public class MgtUserCommunity extends BaseExtDTO {
     @Id
      private String id;

      private String sourceSystem;

      private String mgtUserId;

      private String sourceMgtUserId;

      private String communityId;

      private String sourceSystemCommunityId;

    @Transient
     private String communityName;

    @Transient
    private String companyId;

    @Transient
    private String companyName;

    @Transient
    private String userName;

    @Transient
    private String mobile;

    @Transient
    private String communityCode;
    @Transient
    private String cityName;
    @Transient
    private String address;

    @Transient
    private String serverUrl;

    @Transient
    private String[] selectIds;//选择的小区id

    @Transient
    private String[] selectUserIds;//选择的人员id

    public String getCommunityCode() {
        return communityCode;
    }

    public void setCommunityCode(String communityCode) {
        this.communityCode = communityCode;
    }

    public String getServerUrl() {
        return serverUrl;
    }

    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }

    public String[] getSelectIds() {
        return selectIds;
    }

    public void setSelectIds(String[] selectIds) {
        this.selectIds = selectIds;
    }

    public String[] getSelectUserIds() {
        return selectUserIds;
    }

    public void setSelectUserIds(String[] selectUserIds) {
        this.selectUserIds = selectUserIds;
    }

    public String getCommunityName() {
        return communityName;
    }

    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }

    public String getCompanyId() {
        return companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setSourceSystem(String sourceSystem){
         this.sourceSystem = sourceSystem;
     }

     public String getSourceSystem(){
         return sourceSystem;
     }

    public String getMgtUserId() {
        return mgtUserId;
    }

    public void setMgtUserId(String mgtUserId) {
        this.mgtUserId = mgtUserId;
    }

    public void setCommunityId(String communityId){
         this.communityId = communityId;
     }

     public String getCommunityId(){
         return communityId;
     }

     public void setSourceSystemCommunityId(String sourceSystemCommunityId){
         this.sourceSystemCommunityId = sourceSystemCommunityId;
     }

     public String getSourceSystemCommunityId(){
         return sourceSystemCommunityId;
     }

	public String getSourceMgtUserId() {
		return sourceMgtUserId;
	}

	public void setSourceMgtUserId(String sourceMgtUserId) {
		this.sourceMgtUserId = sourceMgtUserId;
	}

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
