package com.cmig.future.csportal.module.pay.refund.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "csp_order_form_refund")
public class OrderFormRefund extends BaseDTO {
    @Id
    @GeneratedValue
    private Long id;

    private String refundId;

    private String refundOrderNo;

    private Long amount;

    private String status;

    private Date timeSucceed;

    private String description;

    private String failureCode;

    private String failureMsg;

    private String metadata;

    private String chargeId;

    @NotNull
    private String backUrl;

    @NotNull
    private Long orderId;

    @NotEmpty
    private String orderNumber;

    private String transactionNo;

    private String fundingSource;
    
    @Transient
    private Long refundNotifyId;
    @Transient
    private String refundNotifyStatus;
    @Transient
    private Long notifyTimes;
    @Transient
    private Date timeNotified;
    @Transient
    private Date timeNextNotify;
    
    public Long getRefundNotifyId() {
        return refundNotifyId;
    }

    public void setRefundNotifyId(Long refundNotifyId) {
        this.refundNotifyId = refundNotifyId;
    }

    public String getRefundNotifyStatus() {
        return refundNotifyStatus;
    }

    public void setRefundNotifyStatus(String refundNotifyStatus) {
        this.refundNotifyStatus = refundNotifyStatus;
    }

    public Long getNotifyTimes() {
        return notifyTimes;
    }

    public void setNotifyTimes(Long notifyTimes) {
        this.notifyTimes = notifyTimes;
    }

    public Date getTimeNotified() {
        return timeNotified;
    }

    public void setTimeNotified(Date timeNotified) {
        this.timeNotified = timeNotified;
    }

    public Date getTimeNextNotify() {
        return timeNextNotify;
    }

    public void setTimeNextNotify(Date timeNextNotify) {
        this.timeNextNotify = timeNextNotify;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    public String getRefundId() {
        return refundId;
    }

    public void setRefundOrderNo(String refundOrderNo) {
        this.refundOrderNo = refundOrderNo;
    }

    public String getRefundOrderNo() {
        return refundOrderNo;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public Long getAmount() {
        return amount;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setTimeSucceed(Date timeSucceed) {
        this.timeSucceed = timeSucceed;
    }

    public Date getTimeSucceed() {
        return timeSucceed;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setFailureCode(String failureCode) {
        this.failureCode = failureCode;
    }

    public String getFailureCode() {
        return failureCode;
    }

    public void setFailureMsg(String failureMsg) {
        this.failureMsg = failureMsg;
    }

    public String getFailureMsg() {
        return failureMsg;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }

    public String getMetadata() {
        return metadata;
    }

    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    public String getChargeId() {
        return chargeId;
    }

    public String getBackUrl() {
        return backUrl;
    }

    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setTransactionNo(String transactionNo) {
        this.transactionNo = transactionNo;
    }

    public String getTransactionNo() {
        return transactionNo;
    }

    public void setFundingSource(String fundingSource) {
        this.fundingSource = fundingSource;
    }

    public String getFundingSource() {
        return fundingSource;
    }

}