package com.cmig.future.csportal.module.pay.refund.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_order_form_refund_notify_mc")
public class OrderFormRefundNotifyMc extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private Long refundOrderId;

     @NotEmpty
      private String status;

      private Long times;

      private Date timeNotified;

      private Date timeNextNotify;

    @Transient
    private String backUrl;

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

    public Long getRefundOrderId() {
        return refundOrderId;
    }

    public void setRefundOrderId(Long refundOrderId) {
        this.refundOrderId = refundOrderId;
    }

    public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setTimes(Long times){
         this.times = times;
     }

     public Long getTimes(){
         return times;
     }

     public void setTimeNotified(Date timeNotified){
         this.timeNotified = timeNotified;
     }

     public Date getTimeNotified(){
         return timeNotified;
     }

     public void setTimeNextNotify(Date timeNextNotify){
         this.timeNextNotify = timeNextNotify;
     }

     public Date getTimeNextNotify(){
         return timeNextNotify;
     }

    public String getBackUrl() {
        return backUrl;
    }

    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }
}
