package com.cmig.future.csportal.module.villager.order.dto;

/**Auto Generated By Hap Code Generator**/
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.cmig.future.csportal.module.villager.good.dto.VillagerGood;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_villager_order")
public class VillagerOrder extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String appUserId;

     @NotEmpty
      private String orderNumber;

     @NotNull
      private Long orderAmount;

     @NotNull
      private Long discountAmount;

     @NotNull
      private Long integralAmount;

     @NotNull
      private Long payableAmount;

      private Long paidAmount;

      private Date timeExpire;

      private Date timePaid;

      private Date timeSend;

      private Date timeSettle;

    @NotEmpty
      private String goodId;

      @Transient
      private VillagerGood good;

     @NotNull
      private Long goodNum;
    @NotNull
      private String clientIp;

     @NotEmpty
      private String payStatus;

      private String orderStatus;

      private String orderType;

      private String description;

      @Transient
      private String mobile;
      @Transient
      private String userName;

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAppUserId(String appUserId){
         this.appUserId = appUserId;
     }

     public String getAppUserId(){
         return appUserId;
     }

     public void setOrderNumber(String orderNumber){
         this.orderNumber = orderNumber;
     }

     public String getOrderNumber(){
         return orderNumber;
     }

     public void setOrderAmount(Long orderAmount){
         this.orderAmount = orderAmount;
     }

     public Long getOrderAmount(){
         return orderAmount;
     }

     public void setDiscountAmount(Long discountAmount){
         this.discountAmount = discountAmount;
     }

     public Long getDiscountAmount(){
         return discountAmount;
     }

     public void setIntegralAmount(Long integralAmount){
         this.integralAmount = integralAmount;
     }

     public Long getIntegralAmount(){
         return integralAmount;
     }

     public void setPayableAmount(Long payableAmount){
         this.payableAmount = payableAmount;
     }

     public Long getPayableAmount(){
         return payableAmount;
     }

     public void setPaidAmount(Long paidAmount){
         this.paidAmount = paidAmount;
     }

     public Long getPaidAmount(){
         return paidAmount;
     }

     public void setTimeExpire(Date timeExpire){
         this.timeExpire = timeExpire;
     }

     public Date getTimeExpire(){
         return timeExpire;
     }

     public void setTimePaid(Date timePaid){
         this.timePaid = timePaid;
     }

     public Date getTimePaid(){
         return timePaid;
     }

     public void setTimeSend(Date timeSend){
         this.timeSend = timeSend;
     }

     public Date getTimeSend(){
         return timeSend;
     }

     public void setTimeSettle(Date timeSettle){
         this.timeSettle = timeSettle;
     }

     public Date getTimeSettle(){
         return timeSettle;
     }

     public void setGoodId(String goodId){
         this.goodId = goodId;
     }

     public String getGoodId(){
         return goodId;
     }

    public VillagerGood getGood() {
        return good;
    }

    public void setGood(VillagerGood good) {
        this.good = good;
    }

    public void setGoodNum(Long goodNum){
         this.goodNum = goodNum;
     }

     public Long getGoodNum(){
         return goodNum;
     }

     public void setClientIp(String clientIp){
         this.clientIp = clientIp;
     }

     public String getClientIp(){
         return clientIp;
     }

     public void setPayStatus(String payStatus){
         this.payStatus = payStatus;
     }

     public String getPayStatus(){
         return payStatus;
     }

     public void setOrderStatus(String orderStatus){
         this.orderStatus = orderStatus;
     }

     public String getOrderStatus(){
         return orderStatus;
     }

     public void setOrderType(String orderType){
         this.orderType = orderType;
     }

     public String getOrderType(){
         return orderType;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}
