package com.cmig.future.csportal.module.pay.order.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "csp_order_form_line")
public class OrderFormLine extends BaseDTO {
     @Id
     @GeneratedValue
      private Long lineId;

     @NotNull
      private Long orderId;

     @NotNull
      private Long receivableId;


     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setOrderId(Long orderId){
         this.orderId = orderId;
     }

     public Long getOrderId(){
         return orderId;
     }

     public void setReceivableId(Long receivableId){
         this.receivableId = receivableId;
     }

     public Long getReceivableId(){
         return receivableId;
     }

     }
