package com.cmig.future.csportal.module.pay.order.dto;

import com.cmig.future.csportal.common.utils.Arith;
import com.cmig.future.csportal.common.utils.excel.annotation.ExcelField;
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * Auto Generated By Hap Code Generator
 **/

public class OrderFormExcel extends BaseExtDTO {


    @NotEmpty
    private String orderNumber;

    private String payChannel;

    @NotNull
    private Long orderAmount;
    private Long paidAmount;
    private Long discountAmount;
    private Long integralAmount;
    private Long payableAmount;

	@JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date timePaid;


    private String subject;

    private String body;

    private String transeq;

    @NotEmpty
    private String clientIp;

    @NotEmpty
    private String payStatus;

    private String orderStatus;

    private String orderType;

    private String description;
    private String merchantNo;
	@JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date creationDate;
    @Transient
    private String hasRefunds;
    @Transient
    private String userName;
    @Transient
    private String mobile;


	@ExcelField(title = "订单号", align = 2, sort = 10, required = true)
	public String getOrderNumber() {
		return orderNumber;
	}

	@ExcelField(title = "支付渠道",dictType="PAY.CHANNEL", align = 2, sort = 20, required = true)
	public String getPayChannel() {
		return payChannel;
	}

	@ExcelField(title = "订单金额(元)", align = 2, sort = 30, required = true)
	public double getOrderAmount() {
		return Arith.div(new Double(orderAmount==null?0:orderAmount),new Double(100),2);
	}

	@ExcelField(title = "折扣金额(元)", align = 2, sort = 31, required = true)
	public double getDiscountAmount() {
		return Arith.div(new Double(discountAmount==null?0:discountAmount),new Double(100),2);
	}

	@ExcelField(title = "积分抵扣金额(元)", align = 2, sort = 32, required = true)
	public double getIntegralAmount() {
		return Arith.div(new Double(integralAmount==null?0:integralAmount),new Double(100),2);
	}

	@ExcelField(title = "应付金额(元)", align = 2, sort = 33, required = true)
	public double getPayableAmount() {
		return Arith.div(new Double(payableAmount==null?0:payableAmount),new Double(100),2);
	}

	@ExcelField(title = "已付金额(元)", align = 2, sort = 35, required = true)
	public double getPaidAmount() {
		return Arith.div(new Double(paidAmount==null?0:paidAmount),new Double(100),2);
	}

	@ExcelField(title = "支付时间", align = 2, sort = 50, required = true)
	public Date getTimePaid() {
		return timePaid;
	}

	public String getSubject() {
		return subject;
	}

	public String getBody() {
		return body;
	}

	@ExcelField(title = "渠道流水号", align = 2, sort = 80, required = true)
	public String getTranseq() {
		return transeq;
	}

	//@ExcelField(title = "客户端ip", align = 2, sort = 90, required = true)
	public String getClientIp() {
		return clientIp;
	}

	@ExcelField(title = "支付状态", dictType="PAY.STATUS",align = 2, sort = 60, required = true)
	public String getPayStatus() {
		return payStatus;
	}

	public String getOrderStatus() {
		return orderStatus;
	}

	@ExcelField(title = "订单类型", dictType="CSP.PAY.ORDER_TYPE",align = 2, sort = 15, required = true)
	public String getOrderType() {
		return orderType;
	}

	public String getDescription() {
		return description;
	}

	@ExcelField(title = "商户", dictType="CSP.MERCHANT_NO",align = 2, sort = 70, required = true)
	public String getMerchantNo() {
		return merchantNo;
	}

	@Override
	@ExcelField(title = "下单时间", align = 2, sort = 49, required = true)
	public Date getCreationDate() {
		return creationDate;
	}

	public String getHasRefunds() {
		return hasRefunds;
	}

	public String getUserName() {
		return userName;
	}


	public String getMobile() {
		return mobile;
	}


	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public void setPayChannel(String payChannel) {
		this.payChannel = payChannel;
	}

	public void setOrderAmount(Long orderAmount) {
		this.orderAmount = orderAmount;
	}

	public void setPaidAmount(Long paidAmount) {
		this.paidAmount = paidAmount;
	}

	public void setDiscountAmount(Long discountAmount) {
		this.discountAmount = discountAmount;
	}

	public void setIntegralAmount(Long integralAmount) {
		this.integralAmount = integralAmount;
	}

	public void setPayableAmount(Long payableAmount) {
		this.payableAmount = payableAmount;
	}

	public void setTimePaid(Date timePaid) {
		this.timePaid = timePaid;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public void setTranseq(String transeq) {
		this.transeq = transeq;
	}

	public void setClientIp(String clientIp) {
		this.clientIp = clientIp;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setMerchantNo(String merchantNo) {
		this.merchantNo = merchantNo;
	}

	@Override
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public void setHasRefunds(String hasRefunds) {
		this.hasRefunds = hasRefunds;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
