package com.cmig.future.csportal.module.pay.order.dto;

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.cmig.future.csportal.module.lifepay.dto.LifePayBill;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * Auto Generated By Hap Code Generator
 **/

@ExtensionAttribute(disable = true)
@Table(name = "csp_order_form")
public class OrderForm extends BaseExtDTO {
    @Id
    @GeneratedValue
    private Long id;

    @NotEmpty
    private String chargeId;//ping app id

    @NotEmpty
    private String appUserId;

    @NotEmpty
    private String orderNumber;

    private String payChannel;

    @NotEmpty
    private String currency;

    @NotNull
    private Long orderAmount;

    private Long paidAmount;
    private Long discountAmount;
    
    private Long integralAmount;
    
    private Long payableAmount;

    private Date timeExpire;

    private Date timePaid;

    private Date timeSettle;

    private String subject;

    private String body;

    private String transeq;

    private String frontUrl;

    @NotEmpty
    private String backUrl;

    @NotEmpty
    private String clientIp;

    @NotEmpty
    private String appId;

    @NotEmpty
    private String sourceSystem;

    @NotEmpty
    private String sourceOrderNumber;

    @NotEmpty
    private String payStatus;

    private String orderStatus;

    private String orderType;

    private String description;

    private String merchantNo;
    
    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date startDate;

    @Transient
    @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
    private Date endDate;

    private Date creationDate;
    
    @Transient
    private String hasRefunds;
    @Transient
    private String userName;
    @Transient
    private String houseName;
    @Transient
    private String communityName;
    @Transient
    private String channelName;
    @Transient
    private String mobile;

	@Transient
	private String wxOpenId;

	@Transient
	private String successUrl;

	@Transient
	private LifePayBill lifePayBill;

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getHouseName() {
        return houseName;
    }

    public void setHouseName(String houseName) {
        this.houseName = houseName;
    }

    public String getCommunityName() {
        return communityName;
    }

    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }

    public String getChannelName() {
        return channelName;
    }

    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    public Long getDiscountAmount() {
        return discountAmount;
    }

    public void setDiscountAmount(Long discountAmount) {
        this.discountAmount = discountAmount;
    }

    public Long getIntegralAmount() {
        return integralAmount;
    }

    public void setIntegralAmount(Long integralAmount) {
        this.integralAmount = integralAmount;
    }

    public Long getPayableAmount() {
        return payableAmount;
    }

    public void setPayableAmount(Long payableAmount) {
        this.payableAmount = payableAmount;
    }

    public String getHasRefunds() {
        return hasRefunds;
    }

    public void setHasRefunds(String hasRefunds) {
        this.hasRefunds = hasRefunds;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    public String getChargeId() {
        return chargeId;
    }

    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId;
    }

    public String getAppUserId() {
        return appUserId;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }

    public String getPayChannel() {
        return payChannel;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getCurrency() {
        return currency;
    }

    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }

    public Long getOrderAmount() {
        return orderAmount;
    }

    public void setPaidAmount(Long paidAmount) {
        this.paidAmount = paidAmount;
    }

    public Long getPaidAmount() {
        return paidAmount;
    }

    public void setTimeExpire(Date timeExpire) {
        this.timeExpire = timeExpire;
    }

    public Date getTimeExpire() {
        return timeExpire;
    }

    public void setTimePaid(Date timePaid) {
        this.timePaid = timePaid;
    }

    public Date getTimePaid() {
        return timePaid;
    }

    public Date getTimeSettle() {
        return timeSettle;
    }

    public void setTimeSettle(Date timeSettle) {
        this.timeSettle = timeSettle;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getSubject() {
        return subject;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getBody() {
        return body;
    }

    public void setTranseq(String transeq) {
        this.transeq = transeq;
    }

    public String getTranseq() {
        return transeq;
    }

    public void setFrontUrl(String frontUrl) {
        this.frontUrl = frontUrl;
    }

    public String getFrontUrl() {
        return frontUrl;
    }

    public void setBackUrl(String backUrl) {
        this.backUrl = backUrl;
    }

    public String getBackUrl() {
        return backUrl;
    }

    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    public String getClientIp() {
        return clientIp;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getAppId() {
        return appId;
    }

    public void setSourceSystem(String sourceSystem) {
        this.sourceSystem = sourceSystem;
    }

    public String getSourceSystem() {
        return sourceSystem;
    }

    public void setSourceOrderNumber(String sourceOrderNumber) {
        this.sourceOrderNumber = sourceOrderNumber;
    }

    public String getSourceOrderNumber() {
        return sourceOrderNumber;
    }

    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus;
    }

    public String getPayStatus() {
        return payStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getOrderStatus() {
        return orderStatus;
    }

    public String getOrderType() {
        return orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

	public String getWxOpenId() {
		return wxOpenId;
	}

	public void setWxOpenId(String wxOpenId) {
		this.wxOpenId = wxOpenId;
	}

	public String getSuccessUrl() {
		return successUrl;
	}

	public void setSuccessUrl(String successUrl) {
		this.successUrl = successUrl;
	}

	public LifePayBill getLifePayBill() {
		return lifePayBill;
	}

	public void setLifePayBill(LifePayBill lifePayBill) {
		this.lifePayBill = lifePayBill;
	}

	public String getMerchantNo() {
		return merchantNo;
	}

	public void setMerchantNo(String merchantNo) {
		this.merchantNo = merchantNo;
	}

	@Transient
	private String channel;

	public String getChannel() {
		return channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}
}
