package com.cmig.future.csportal.module.properties.company.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.core.annotation.Children;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "csp_ljh_base_company")
public class LjhBaseCompany extends BaseExtDTO {
    @Id
    private String companyId;

    private String companyCode;

    @NotEmpty
    private String companyName;

    private String corpId;

    private String addressSecret;

    private String sourceSystemId;

    private String openAppId;

    private String serverUrl;

    private String workWxFlag;

    @Transient
    @Children
    private List<LjhCorpAgent> corpAgents;


    public List<LjhCorpAgent> getCorpAgents() {
        return corpAgents;
    }

    public void setCorpAgents(List<LjhCorpAgent> corpAgents) {
        this.corpAgents = corpAgents;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getCompanyId() {
        return companyId;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCorpId(String corpId) {
        this.corpId = corpId;
    }

    public String getCorpId() {
        return corpId;
    }

    public void setAddressSecret(String addressSecret) {
        this.addressSecret = addressSecret;
    }

    public String getAddressSecret() {
        return addressSecret;
    }

    public void setSourceSystemId(String sourceSystemId) {
        this.sourceSystemId = sourceSystemId;
    }

    public String getSourceSystemId() {
        return sourceSystemId;
    }

    public void setOpenAppId(String openAppId) {
        this.openAppId = openAppId;
    }

    public String getOpenAppId() {
        return openAppId;
    }

    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }

    public String getServerUrl() {
        return serverUrl;
    }

    public void setWorkWxFlag(String workWxFlag) {
        this.workWxFlag = workWxFlag;
    }

    public String getWorkWxFlag() {
        return workWxFlag;
    }

}
