package com.cmig.future.csportal.module.properties.company.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_corp_agent")
public class LjhCorpAgent extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String corpId;

      private String agentNo;

      private String agentType;

      private String agentId;

      private String agentSecret;

      private String messageToken;

      private String tncodingAesKey;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setCorpId(String corpId){
         this.corpId = corpId;
     }

     public String getCorpId(){
         return corpId;
     }

	public String getAgentNo() {
		return agentNo;
	}

	public void setAgentNo(String agentNo) {
		this.agentNo = agentNo;
	}

	public void setAgentType(String agentType){
         this.agentType = agentType;
     }

     public String getAgentType(){
         return agentType;
     }

     public void setAgentId(String agentId){
         this.agentId = agentId;
     }

     public String getAgentId(){
         return agentId;
     }

     public void setAgentSecret(String agentSecret){
         this.agentSecret = agentSecret;
     }

     public String getAgentSecret(){
         return agentSecret;
     }

	public String getMessageToken() {
		return messageToken;
	}

	public void setMessageToken(String messageToken) {
		this.messageToken = messageToken;
	}

	public void setTncodingAesKey(String tncodingAesKey){
         this.tncodingAesKey = tncodingAesKey;
     }

     public String getTncodingAesKey(){
         return tncodingAesKey;
     }

     }
