package com.cmig.future.csportal.module.kpi.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.common.utils.DateUtils;
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_kpi_user")
public class LjhKpiUser extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String appKey;

      private Date kpiDate;

      private Long installations;

      private Long newUsers;

      private Long activeUsers;

      private Long launches;

      @Transient
      private Long days=30l;

	@Transient
	private String kpiDateStr;

	@Transient
	private String groupName;

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAppKey(String appKey){
         this.appKey = appKey;
     }

     public String getAppKey(){
         return appKey;
     }

     public void setKpiDate(Date kpiDate){
         this.kpiDate = kpiDate;
     }

     public Date getKpiDate(){
         return kpiDate;
     }

     public void setInstallations(Long installations){
         this.installations = installations;
     }

     public Long getInstallations(){
         return installations;
     }

     public void setNewUsers(Long newUsers){
         this.newUsers = newUsers;
     }

     public Long getNewUsers(){
         return newUsers;
     }

     public void setActiveUsers(Long activeUsers){
         this.activeUsers = activeUsers;
     }

     public Long getActiveUsers(){
         return activeUsers;
     }

     public void setLaunches(Long launches){
         this.launches = launches;
     }

     public Long getLaunches(){
         return launches;
     }

	public Long getDays() {
		return days;
	}

	public void setDays(Long days) {
		this.days = days;
	}

	public String getKpiDateStr() {
		if(null!=this.kpiDate) {
			return DateUtils.formatDate(this.kpiDate, "yyyy-MM-dd");
		}
		return null;
	}

	public void setKpiDateStr(String kpiDateStr) {
		this.kpiDateStr = kpiDateStr;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
}
