package com.cmig.future.csportal.module.kpi.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.common.utils.DateUtils;
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_kpi_event_group")
public class LjhKpiEventGroup extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String appKey;

      private Date kpiDate;

      private String groupId;

      private String name;

      private String displayName;

      private Long num;

      @Transient
      private String groupName;

	@Transient
	private String kpiDateStr;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAppKey(String appKey){
         this.appKey = appKey;
     }

     public String getAppKey(){
         return appKey;
     }

     public void setKpiDate(Date kpiDate){
         this.kpiDate = kpiDate;
     }

     public Date getKpiDate(){
         return kpiDate;
     }

     public void setGroupId(String groupId){
         this.groupId = groupId;
     }

     public String getGroupId(){
         return groupId;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setDisplayName(String displayName){
         this.displayName = displayName;
     }

     public String getDisplayName(){
         return displayName;
     }

     public void setNum(Long num){
         this.num = num;
     }

     public Long getNum(){
         return num;
     }

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getKpiDateStr() {
     	if(null!=this.kpiDate){
			return DateUtils.formatDate(this.kpiDate, "yyyy-MM-dd");
		}else{
     		return null;
		}
	}

	public void setKpiDateStr(String kpiDateStr) {
		this.kpiDateStr = kpiDateStr;
	}
}
