package com.cmig.future.csportal.module.kpi.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_kpi_duration")
public class LjhKpiDuration extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String appKey;

      private Date kpiDate;

      private String periodType;

      private String dimension;

      private Long num;

      private Double percent;

	private String average;

	@Transient
	private String groupName;

	public String getAverage() {
		return average;
	}

	public void setAverage(String average) {
		this.average = average;
	}

     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAppKey(String appKey){
         this.appKey = appKey;
     }

     public String getAppKey(){
         return appKey;
     }

     public void setKpiDate(Date kpiDate){
         this.kpiDate = kpiDate;
     }

     public Date getKpiDate(){
         return kpiDate;
     }

     public void setPeriodType(String periodType){
         this.periodType = periodType;
     }

     public String getPeriodType(){
         return periodType;
     }

     public void setDimension(String dimension){
         this.dimension = dimension;
     }

     public String getDimension(){
         return dimension;
     }

     public void setNum(Long num){
         this.num = num;
     }

     public Long getNum(){
         return num;
     }

	public Double getPercent() {
		return percent;
	}

	public void setPercent(Double percent) {
		this.percent = percent;
	}

	public String getGroupName() {
		return groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}
}
