package com.cmig.future.csportal.module.kpi.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "csp_umeng_app")
public class UmengApp extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String appKey;

      private String platform;

      private String popular;

      private String name;

      private String groupName;

      private String useGameSdk;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setAppKey(String appKey){
         this.appKey = appKey;
     }

     public String getAppKey(){
         return appKey;
     }

     public void setPlatform(String platform){
         this.platform = platform;
     }

     public String getPlatform(){
         return platform;
     }

     public void setPopular(String popular){
         this.popular = popular;
     }

     public String getPopular(){
         return popular;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setGroupName(String groupName){
         this.groupName = groupName;
     }

     public String getGroupName(){
         return groupName;
     }

     public void setUseGameSdk(String useGameSdk){
         this.useGameSdk = useGameSdk;
     }

     public String getUseGameSdk(){
         return useGameSdk;
     }

     }
