package com.cmig.future.csportal.module.properties.base.structure.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.common.utils.excel.annotation.ExcelField;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

public class MgtStructureImport extends BaseDTO {

     @NotEmpty
      private String structureCode; //编码

     @NotEmpty
      private String parentStructureCode; //父结构

      private String sourceStructureCode; //建筑原始编码

     @NotEmpty
      private String structureName; //节点名称

      @NotEmpty
      private String structureFullName; //建筑名称

      @NotEmpty
      private String structureType; //建筑类型

      private String buildingArea; //建筑面积

      private String paymentArea; //收费面积

      private String useType; //用途

      private String decorationStatus; //装修情况


    @ExcelField(title = "编码(必填)", align = 2, sort = 1, required = true)
    public String getStructureCode(){
        return structureCode;
    }

    public void setStructureCode(String structureCode){
        this.structureCode = structureCode;
    }

    @ExcelField(title = "父结构(必填)", align = 2, sort = 10, required = true)
    public String getParentStructureCode() {
        return parentStructureCode;
    }

    public void setParentStructureCode(String parentStructureCode) {
        this.parentStructureCode = parentStructureCode;
    }

    @ExcelField(title = "建筑原始编码", align = 2, sort = 20, required = false)
    public String getSourceStructureCode(){
        return sourceStructureCode;
    }

    public void setSourceStructureCode(String sourceStructureCode){
        this.sourceStructureCode = sourceStructureCode;
    }

    @ExcelField(title = "节点名称(必填)", align = 2, sort = 30, required = true)
    public String getStructureName(){
        return structureName;
    }

    public void setStructureName(String structureName){
        this.structureName = structureName;
    }

    @ExcelField(title = "建筑名称(必填)", align = 2, sort = 40, required = true)
    public String getStructureFullName(){
        return structureFullName;
    }

    public void setStructureFullName(String structureFullName){
        this.structureFullName = structureFullName;
    }

    @ExcelField(title = "建筑类型(必填)", dictType="MGT.STRUCTURE_TYPE", align = 2, sort = 50, required = true)
    public String getStructureType(){
        return structureType;
    }

    public void setStructureType(String structureType){
        this.structureType = structureType;
    }

    @ExcelField(title = "建筑面积", align = 2, sort = 60, required = false)
    public String getBuildingArea() {
        return buildingArea;
    }

    public void setBuildingArea(String buildingArea) {
        this.buildingArea = buildingArea;
    }

    @ExcelField(title = "收费面积", align = 2, sort = 70, required = false)
    public String getPaymentArea() {
        return paymentArea;
    }

    public void setPaymentArea(String paymentArea) {
        this.paymentArea = paymentArea;
    }

    @ExcelField(title = "用途", dictType="MGT.HOUSE_USE_TYPE", align = 2, sort = 80, required = false)
    public String getUseType() {
        return useType;
    }

    public void setUseType(String useType) {
        this.useType = useType;
    }

    @ExcelField(title = "装修情况", align = 2, sort = 90, required = false)
    public String getDecorationStatus() {
        return decorationStatus;
    }

    public void setDecorationStatus(String decorationStatus) {
        this.decorationStatus = decorationStatus;
    }


     }
