package com.cmig.future.csportal.module.properties.base.structure.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "csp_mgt_structure")
public class MgtStructure extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long structureId;

     @NotNull
      private Long versionId;

     @NotNull
      private Long parentStructureId;

     @NotEmpty
      private String communityId;

     @NotEmpty
      private String structureCode;

     @NotEmpty
      private String structureName;

      private String structureNickName;

      private String structureFullName;

      private String structureType;

      private String businessType;

      private String status;

      private String sourceStructureCode;

      @Transient
      private String structureParentFullName;

    public String getStructureParentFullName() {
        return structureParentFullName;
    }

    public void setStructureParentFullName(String structureParentFullName) {
        this.structureParentFullName = structureParentFullName;
    }

    public void setStructureId(Long structureId){
         this.structureId = structureId;
     }

     public Long getStructureId(){
         return structureId;
     }

     public void setVersionId(Long versionId){
         this.versionId = versionId;
     }

     public Long getVersionId(){
         return versionId;
     }

     public void setParentStructureId(Long parentStructureId){
         this.parentStructureId = parentStructureId;
     }

     public Long getParentStructureId(){
         return parentStructureId;
     }

     public void setCommunityId(String communityId){
         this.communityId = communityId;
     }

     public String getCommunityId(){
         return communityId;
     }

     public void setStructureCode(String structureCode){
         this.structureCode = structureCode;
     }

     public String getStructureCode(){
         return structureCode;
     }

     public void setStructureName(String structureName){
         this.structureName = structureName;
     }

     public String getStructureName(){
         return structureName;
     }

     public void setStructureNickName(String structureNickName){
         this.structureNickName = structureNickName;
     }

     public String getStructureNickName(){
         return structureNickName;
     }

     public void setStructureFullName(String structureFullName){
         this.structureFullName = structureFullName;
     }

     public String getStructureFullName(){
         return structureFullName;
     }

     public void setStructureType(String structureType){
         this.structureType = structureType;
     }

     public String getStructureType(){
         return structureType;
     }

     public void setBusinessType(String businessType){
         this.businessType = businessType;
     }

     public String getBusinessType(){
         return businessType;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setSourceStructureCode(String sourceStructureCode){
         this.sourceStructureCode = sourceStructureCode;
     }

     public String getSourceStructureCode(){
         return sourceStructureCode;
     }

     }
