package com.cmig.future.csportal.module.sys.city.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * LjhSysArea
 * 城市
 * @author bubu
 *
 * 2017-3-21
 */
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_sys_area")
public class LjhSysArea extends BaseDTO {
     @Id
      private String id;

      private String parentId;

     @NotEmpty
      private String parentIds;

     @NotEmpty
      private String name;

      private Long sort;

      private String code;

      private String type;

      private String remarks;

      private String delFlag;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setParentId(String parentId){
         this.parentId = parentId;
     }

     public String getParentId(){
         return parentId;
     }

     public void setParentIds(String parentIds){
         this.parentIds = parentIds;
     }

     public String getParentIds(){
         return parentIds;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setSort(Long sort){
         this.sort = sort;
     }

     public Long getSort(){
         return sort;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setRemarks(String remarks){
         this.remarks = remarks;
     }

     public String getRemarks(){
         return remarks;
     }

     public void setDelFlag(String delFlag){
         this.delFlag = delFlag;
     }

     public String getDelFlag(){
         return delFlag;
     }

     }
