package com.cmig.future.csportal.module.villager.voucher.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xl_voucher_receive")
public class VoucherReceive extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private Long voucherId;

      private String appUserId;
      
      @Transient
      private String appUserName;
      
      @Transient
      private String userIcon;
      
      @Transient
      private String communityName;
      
      @Transient
      private String count;

      @Transient
      private String content;
      
      private String mgtUserId;

      private String receiveWay;

      private String image;

      private String status;

      private String isused;

      @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
      private Date useDate;

      @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
      private Date limitDate;
      
      private String barCode;
      
      private String mobile;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setVoucherId(Long voucherId){
         this.voucherId = voucherId;
     }

     public Long getVoucherId(){
         return voucherId;
     }

     public void setAppUserId(String appUserId){
         this.appUserId = appUserId;
     }

     public String getAppUserId(){
         return appUserId;
     }

     public void setMgtUserId(String mgtUserId){
         this.mgtUserId = mgtUserId;
     }

     public String getMgtUserId(){
         return mgtUserId;
     }

     public void setReceiveWay(String receiveWay){
         this.receiveWay = receiveWay;
     }

     public String getReceiveWay(){
         return receiveWay;
     }

     public void setImage(String image){
         this.image = image;
     }

     public String getImage(){
         return image;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setIsused(String isused){
         this.isused = isused;
     }

     public String getIsused(){
         return isused;
     }

     public void setUseDate(Date useDate){
         this.useDate = useDate;
     }

     public Date getUseDate(){
         return useDate;
     }

     public void setLimitDate(Date limitDate){
         this.limitDate = limitDate;
     }

     public Date getLimitDate(){
         return limitDate;
     }

	public String getBarCode() {
		return barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	public String getAppUserName() {
		return appUserName;
	}

	public void setAppUserName(String appUserName) {
		this.appUserName = appUserName;
	}

	public String getUserIcon() {
		return userIcon;
	}

	public void setUserIcon(String userIcon) {
		this.userIcon = userIcon;
	}

	public String getCommunityName() {
		return communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	

     }
