package com.cmig.future.csportal.module.villager.voucher.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "xl_voucher_info")
public class VoucherInfo extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String exchangeCode;

      private String title;

      private String content;

      private String amount;
      
      private String scores;

      private String voucherType;

      private String goodCode;

      private String image;

      private String barCode;

      private String status;

      @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
      @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
      private Date limitDate;
      
      @Transient
      private Long voucher_ReceiveId;
      
      @Transient
      private Long isused;
      
      private String describes;

      private Long validDays;

      private String count;

      private String cycle;

      private String cycleDesc;

      private String useDesc;

      private String usePlat;

      @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
      @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
      private Date startDate;

      private String useLimit;

      private String useWay;

      private String coverTitle;

      private String coverDesc;
      
      @Transient
      private Object twoBarCodesJson;
      
      private String stocks;
      
      private String equalsPrice;
      
      private String units;
      
      
     public Object getTwoBarCodesJson() {
		return twoBarCodesJson;
	}

	public void setTwoBarCodesJson(Object twoBarCodesJson) {
		this.twoBarCodesJson = twoBarCodesJson;
	}

	public Long getIsused() {
		return isused;
	}

	public void setIsused(Long isused) {
		this.isused = isused;
	}

	public Long getVoucher_ReceiveId() {
		return voucher_ReceiveId;
	}

	public void setVoucher_ReceiveId(Long voucher_ReceiveId) {
		this.voucher_ReceiveId = voucher_ReceiveId;
	}

	public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setExchangeCode(String exchangeCode){
         this.exchangeCode = exchangeCode;
     }

     public String getExchangeCode(){
         return exchangeCode;
     }

     public void setTitle(String title){
         this.title = title;
     }

     public String getTitle(){
         return title;
     }

     public void setContent(String content){
         this.content = content;
     }

     public String getContent(){
         return content;
     }

     public void setAmount(String amount){
         this.amount = amount;
     }

     public String getAmount(){
         return amount;
     }

     public void setVoucherType(String voucherType){
         this.voucherType = voucherType;
     }

     public String getVoucherType(){
         return voucherType;
     }

     public void setGoodCode(String goodCode){
         this.goodCode = goodCode;
     }

     public String getGoodCode(){
         return goodCode;
     }

     public void setImage(String image){
         this.image = image;
     }

     public String getImage(){
         return image;
     }

     public void setBarCode(String barCode){
         this.barCode = barCode;
     }

     public String getBarCode(){
         return barCode;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     public void setLimitDate(Date limitDate){
         this.limitDate = limitDate;
     }

     public Date getLimitDate(){
         return limitDate;
     }

	public String getDescribes() {
		return describes;
	}

	public void setDescribes(String describes) {
		this.describes = describes;
	}

	

	

	public Long getValidDays() {
		return validDays;
	}

	public void setValidDays(Long validDays) {
		this.validDays = validDays;
	}

	public String getCount() {
		return count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getCycle() {
		return cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	public String getCycleDesc() {
		return cycleDesc;
	}

	public void setCycleDesc(String cycleDesc) {
		this.cycleDesc = cycleDesc;
	}

	public String getUseDesc() {
		return useDesc;
	}

	public void setUseDesc(String useDesc) {
		this.useDesc = useDesc;
	}

	public String getUsePlat() {
		return usePlat;
	}

	public void setUsePlat(String usePlat) {
		this.usePlat = usePlat;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public String getUseLimit() {
		return useLimit;
	}

	public void setUseLimit(String useLimit) {
		this.useLimit = useLimit;
	}

	public String getUseWay() {
		return useWay;
	}

	public void setUseWay(String useWay) {
		this.useWay = useWay;
	}

	public String getCoverTitle() {
		return coverTitle;
	}

	public void setCoverTitle(String coverTitle) {
		this.coverTitle = coverTitle;
	}

	public String getCoverDesc() {
		return coverDesc;
	}

	public void setCoverDesc(String coverDesc) {
		this.coverDesc = coverDesc;
	}

	public String getScores() {
		return scores;
	}

	public void setScores(String scores) {
		this.scores = scores;
	}

	public String getStocks() {
		return stocks;
	}

	public void setStocks(String stocks) {
		this.stocks = stocks;
	}

	public String getEqualsPrice() {
		return equalsPrice;
	}

	public void setEqualsPrice(String equalsPrice) {
		this.equalsPrice = equalsPrice;
	}

	public String getUnits() {
		return units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

     }
