package com.cmig.future.csportal.module.villager.voucher.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.common.utils.excel.annotation.ExcelField;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.core.BaseConstants;

import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
public class VoucherReceiveExcel extends BaseDTO {

      private String appUserName;
      
      @JsonFormat(pattern = BaseConstants.DATE_TIME_FORMAT)
      private Date useDate;

      private String mobile;

     public void setUseDate(Date useDate){
         this.useDate = useDate;
     }

     //@ExcelField(title = "使用日期", align = 2, sort = 30, required = true)
     public Date getUseDate(){
         return useDate;
     }

     @ExcelField(title = "用户名", align = 2, sort = 20, required = true)
	public String getAppUserName() {
		return appUserName;
	}

	public void setAppUserName(String appUserName) {
		this.appUserName = appUserName;
	}

	@ExcelField(title = "手机号", align = 2, sort = 10, required = true)
	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

  }
