package com.cmig.future.csportal.module.properties.base.customer.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "csp_bp_general")
public class BpGeneral extends BaseDTO {
     @Id
     @GeneratedValue
      private Long bpId;

      private String bpCode;

     @NotEmpty
      private String bpName;

      private String bpNickName;

     @NotEmpty
      private String idType;

     @NotEmpty
      private String idNo;

      private String photo;

      private String mobile;

      private String phone;

      private String email;

      private String gender;

      private Date birthday;

      private Long age;
      
      @Transient
      private Long bpOwnerId;
      

     public Long getBpOwnerId() {
        return bpOwnerId;
    }

    public void setBpOwnerId(Long bpOwnerId) {
        this.bpOwnerId = bpOwnerId;
    }

    public void setBpId(Long bpId){
         this.bpId = bpId;
     }

     public Long getBpId(){
         return bpId;
     }

     public void setBpCode(String bpCode){
         this.bpCode = bpCode;
     }

     public String getBpCode(){
         return bpCode;
     }

     public void setBpName(String bpName){
         this.bpName = bpName;
     }

     public String getBpName(){
         return bpName;
     }

     public void setBpNickName(String bpNickName){
         this.bpNickName = bpNickName;
     }

     public String getBpNickName(){
         return bpNickName;
     }

     public void setIdType(String idType){
         this.idType = idType;
     }

     public String getIdType(){
         return idType;
     }

     public void setIdNo(String idNo){
         this.idNo = idNo;
     }

     public String getIdNo(){
         return idNo;
     }

     public void setPhoto(String photo){
         this.photo = photo;
     }

     public String getPhoto(){
         return photo;
     }

     public void setMobile(String mobile){
         this.mobile = mobile;
     }

     public String getMobile(){
         return mobile;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

     public void setEmail(String email){
         this.email = email;
     }

     public String getEmail(){
         return email;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     public void setBirthday(Date birthday){
         this.birthday = birthday;
     }

     public Date getBirthday(){
         return birthday;
     }

     public void setAge(Long age){
         this.age = age;
     }

     public Long getAge(){
         return age;
     }

     }
