package com.cmig.future.csportal.module.properties.base.customer.dto;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.List;

/**
 * Auto Generated By Hap Code Generator
 **/

@ExtensionAttribute(disable = true)
@Table(name = "csp_bp_owner")
public class BpOwner extends BaseDTO {
    @Id
    @GeneratedValue
    private Long bpOwnerId;

    @NotNull
    private Long bpId;

    // 伙伴基表
    @Transient
    private String bpCode;

    @NotEmpty
    @Transient
    private String bpName;

    @Transient
    private String bpNickName;

    @NotEmpty
    @Transient
    private String idType;

    @NotEmpty
    @Transient
    private String idNo;

    @Transient
    private String photo;

    @Transient
    private String mobile;

    @Transient
    private String phone;

    @Transient
    private String email;

    @Transient
    private String gender;

    @Transient
    private Date birthday;

    @Transient
    private Long age;

    @Transient
    List<BpHouseMap> houseMapList;

    public List<BpHouseMap> getHouseMapList() {
        return houseMapList;
    }

    public void setHouseMapList(List<BpHouseMap> houseMapList) {
        this.houseMapList = houseMapList;
    }

    public void setBpOwnerId(Long bpOwnerId) {
        this.bpOwnerId = bpOwnerId;
    }

    public Long getBpOwnerId() {
        return bpOwnerId;
    }

    public void setBpId(Long bpId) {
        this.bpId = bpId;
    }

    public Long getBpId() {
        return bpId;
    }

    public String getBpCode() {
        return bpCode;
    }

    public void setBpCode(String bpCode) {
        this.bpCode = bpCode;
    }

    public String getBpName() {
        return bpName;
    }

    public void setBpName(String bpName) {
        this.bpName = bpName;
    }

    public String getBpNickName() {
        return bpNickName;
    }

    public void setBpNickName(String bpNickName) {
        this.bpNickName = bpNickName;
    }

    public String getIdType() {
        return idType;
    }

    public void setIdType(String idType) {
        this.idType = idType;
    }

    public String getIdNo() {
        return idNo;
    }

    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Long getAge() {
        return age;
    }

    public void setAge(Long age) {
        this.age = age;
    }
    
}
