package com.cmig.future.csportal.module.properties.base.map.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
@ExtensionAttribute(disable=true)
@Table(name = "csp_structure_building_map")
public class StructureBuildingMap extends BaseDTO {
     @Id
     @GeneratedValue
      private Long mapId;

     @NotEmpty
      private String buildingType;

     @NotNull
      private Long structureId;

     @NotNull
      private Long buildingId;

      private String status;

      @Transient
      private Long versionId;

    public Long getVersionId() {
        return versionId;
    }

    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    public void setMapId(Long mapId){
         this.mapId = mapId;
     }

     public Long getMapId(){
         return mapId;
     }

     public void setBuildingType(String buildingType){
         this.buildingType = buildingType;
     }

     public String getBuildingType(){
         return buildingType;
     }

     public void setStructureId(Long structureId){
         this.structureId = structureId;
     }

     public Long getStructureId(){
         return structureId;
     }

     public void setBuildingId(Long buildingId){
         this.buildingId = buildingId;
     }

     public Long getBuildingId(){
         return buildingId;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     }
