package com.cmig.future.csportal.module.cooperate.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_cooperate")
public class Cooperate extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String merchantName;

      private String address;

      private String operateType;

      private String phone;

      private String appUserId;

      private Long createdBy;

      private Date creationDate;



     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setMerchantName(String merchantName){
         this.merchantName = merchantName;
     }

     public String getMerchantName(){
         return merchantName;
     }

     public void setAddress(String address){
         this.address = address;
     }

     public String getAddress(){
         return address;
     }

     public void setOperateType(String operateType){
         this.operateType = operateType;
     }

     public String getOperateType(){
         return operateType;
     }

     public void setPhone(String phone){
         this.phone = phone;
     }

     public String getPhone(){
         return phone;
     }

    public String getAppUserId() {
        return appUserId;
    }

    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId;
    }

    public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }


    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}
