package com.cmig.future.csportal.module.sys.appconfig.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_app_community_function")
public class AppCommunityFunction extends BaseExtDTO {
	  @Id
      private String id;

      private String delFlag;

      private String cid;

      private String fid;

      private Long number;

      private String authenType;

      private Long createdBy;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setDelFlag(String delFlag){
         this.delFlag = delFlag;
     }

     public String getDelFlag(){
         return delFlag;
     }

     public void setCid(String cid){
         this.cid = cid;
     }

     public String getCid(){
         return cid;
     }

     public void setFid(String fid){
         this.fid = fid;
     }

     public String getFid(){
         return fid;
     }

     public void setNumber(Long number){
         this.number = number;
     }

     public Long getNumber(){
         return number;
     }

     public void setAuthenType(String authenType){
         this.authenType = authenType;
     }

     public String getAuthenType(){
         return authenType;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		AppCommunityFunction that = (AppCommunityFunction) o;

		if (cid != null ? !cid.equals(that.cid) : that.cid != null) return false;
		return fid != null ? fid.equals(that.fid) : that.fid == null;
	}

	@Override
	public int hashCode() {
		int result = cid != null ? cid.hashCode() : 0;
		result = 31 * result + (fid != null ? fid.hashCode() : 0);
		return result;
	}
}
