package com.cmig.future.csportal.module.sys.appconfig.dto;

/**Auto Generated By Hap Code Generator**/
import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@ExtensionAttribute(disable=true)
@Table(name = "csp_ljh_app_config_function")
public class AppConfigFunction extends BaseExtDTO{
      @Id
      private String id;

      private String delFlag;



      private String functionCode;

      private String functionName;

      private String functionRemark;

      private String functionType;

      private String functionSort;

      private String functionUrl;

      private String functionFlag;

      private String functionAddType;

      private String functionImg;

      private String functionStatus;

      private String loginStatus;

      private String relevanceStatus;

      private Long createdBy;




    @Transient
    private String communityId;//小区id

    @Transient
    private String functionNumber;//排序

    @Transient
    private String cfid;


     public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setDelFlag(String delFlag){
         this.delFlag = delFlag;
     }

     public String getDelFlag(){
         return delFlag;
     }

     public void setFunctionCode(String functionCode){
         this.functionCode = functionCode;
     }

     public String getFunctionCode(){
         return functionCode;
     }

     public void setFunctionName(String functionName){
         this.functionName = functionName;
     }

     public String getFunctionName(){
         return functionName;
     }

     public void setFunctionType(String functionType){
         this.functionType = functionType;
     }

     public String getFunctionType(){
         return functionType;
     }

     public void setFunctionSort(String functionSort){
         this.functionSort = functionSort;
     }

     public String getFunctionSort(){
         return functionSort;
     }

     public void setFunctionUrl(String functionUrl){
         this.functionUrl = functionUrl;
     }

     public String getFunctionUrl(){
         return functionUrl;
     }

     public void setFunctionFlag(String functionFlag){
         this.functionFlag = functionFlag;
     }

     public String getFunctionFlag(){
         return functionFlag;
     }

     public void setFunctionAddType(String functionAddType){
         this.functionAddType = functionAddType;
     }

     public String getFunctionAddType(){
         return functionAddType;
     }

     public void setFunctionImg(String functionImg){
         this.functionImg = functionImg;
     }

     public String getFunctionImg(){
         return functionImg;
     }

     public void setFunctionStatus(String functionStatus){
         this.functionStatus = functionStatus;
     }

     public String getFunctionStatus(){
         return functionStatus;
     }

     public void setLoginStatus(String loginStatus){
         this.loginStatus = loginStatus;
     }

     public String getLoginStatus(){
         return loginStatus;
     }

     public void setRelevanceStatus(String relevanceStatus){
         this.relevanceStatus = relevanceStatus;
     }

     public String getRelevanceStatus(){
         return relevanceStatus;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

    public String getCommunityId() {
        return communityId;
    }

    public void setCommunityId(String communityId) {
        this.communityId = communityId;
    }

    public String getFunctionNumber() {
        return functionNumber;
    }

    public void setFunctionNumber(String functionNumber) {
        this.functionNumber = functionNumber;
    }

    public String getCfid() {
        return cfid;
    }

    public void setCfid(String cfid) {
        this.cfid = cfid;
    }

    public String getFunctionRemark() {
        return functionRemark;
    }

    public void setFunctionRemark(String functionRemark) {
        this.functionRemark = functionRemark;
    }
}
