package com.cmig.future.csportal.module.villager.keyword.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "csp_villager_keyword_function")
public class VillagerKeywordFunction extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String keyword;

      private String functionCode;
      private String functionName;

      private Integer weight;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setKeyword(String keyword){
         this.keyword = keyword;
     }

     public String getKeyword(){
         return keyword;
     }

     public void setFunctionCode(String functionCode){
         this.functionCode = functionCode;
     }

     public String getFunctionCode(){
         return functionCode;
     }

    public String getFunctionName() {
        return functionName;
    }

    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}
