package com.cmig.future.csportal.module.villager.wealth.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "xl_animal_cost")
public class AnimalCost extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String typeCode;

      private String muCode;

      private String muArea;

      private Long buildingCost;

      private Long cubCost;

      private Long feedCost;

      private Long landCost;

      private Long drugsCost;

      private Long cleanCost;

      private Long totalYield;

      private Long totalIncome;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTypeCode(String typeCode){
         this.typeCode = typeCode;
     }

     public String getTypeCode(){
         return typeCode;
     }

     public void setMuCode(String muCode){
         this.muCode = muCode;
     }

     public String getMuCode(){
         return muCode;
     }

     public void setMuArea(String muArea){
         this.muArea = muArea;
     }

     public String getMuArea(){
         return muArea;
     }

     public void setBuildingCost(Long buildingCost){
         this.buildingCost = buildingCost;
     }

     public Long getBuildingCost(){
         return buildingCost;
     }

     public void setCubCost(Long cubCost){
         this.cubCost = cubCost;
     }

     public Long getCubCost(){
         return cubCost;
     }

     public void setFeedCost(Long feedCost){
         this.feedCost = feedCost;
     }

     public Long getFeedCost(){
         return feedCost;
     }

     public void setLandCost(Long landCost){
         this.landCost = landCost;
     }

     public Long getLandCost(){
         return landCost;
     }

     public void setDrugsCost(Long drugsCost){
         this.drugsCost = drugsCost;
     }

     public Long getDrugsCost(){
         return drugsCost;
     }

     public void setCleanCost(Long cleanCost){
         this.cleanCost = cleanCost;
     }

     public Long getCleanCost(){
         return cleanCost;
     }

     public void setTotalYield(Long totalYield){
         this.totalYield = totalYield;
     }

     public Long getTotalYield(){
         return totalYield;
     }

     public void setTotalIncome(Long totalIncome){
         this.totalIncome = totalIncome;
     }

     public Long getTotalIncome(){
         return totalIncome;
     }

     }
