package com.cmig.future.csportal.module.villager.wealth.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "xl_animal_type")
public class AnimalType extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String typeCode;

      private String typeName;

      private String itemName;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTypeCode(String typeCode){
         this.typeCode = typeCode;
     }

     public String getTypeCode(){
         return typeCode;
     }

     public void setTypeName(String typeName){
         this.typeName = typeName;
     }

     public String getTypeName(){
         return typeName;
     }

     public void setItemName(String itemName){
         this.itemName = itemName;
     }

     public String getItemName(){
         return itemName;
     }

     }
