package com.cmig.future.csportal.module.villager.wealth.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "xl_plant_cost")
public class PlantCost extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String typeCode;

      private String muCode;

      private String muArea;

      private Long fertilizerCost;

      private Long pesticideCost;

      private Long seedlingsCost;

      private Long bakeCost;

      private Long machineCost;

      private Long landCost;

      private Long totalYield;

      private Long totalIncome;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTypeCode(String typeCode){
         this.typeCode = typeCode;
     }

     public String getTypeCode(){
         return typeCode;
     }

     public void setMuCode(String muCode){
         this.muCode = muCode;
     }

     public String getMuCode(){
         return muCode;
     }

     public void setMuArea(String muArea){
         this.muArea = muArea;
     }

     public String getMuArea(){
         return muArea;
     }

     public void setFertilizerCost(Long fertilizerCost){
         this.fertilizerCost = fertilizerCost;
     }

     public Long getFertilizerCost(){
         return fertilizerCost;
     }

     public void setPesticideCost(Long pesticideCost){
         this.pesticideCost = pesticideCost;
     }

     public Long getPesticideCost(){
         return pesticideCost;
     }

     public void setSeedlingsCost(Long seedlingsCost){
         this.seedlingsCost = seedlingsCost;
     }

     public Long getSeedlingsCost(){
         return seedlingsCost;
     }

     public void setBakeCost(Long bakeCost){
         this.bakeCost = bakeCost;
     }

     public Long getBakeCost(){
         return bakeCost;
     }

     public void setMachineCost(Long machineCost){
         this.machineCost = machineCost;
     }

     public Long getMachineCost(){
         return machineCost;
     }

     public void setLandCost(Long landCost){
         this.landCost = landCost;
     }

     public Long getLandCost(){
         return landCost;
     }

     public void setTotalYield(Long totalYield){
         this.totalYield = totalYield;
     }

     public Long getTotalYield(){
         return totalYield;
     }

     public void setTotalIncome(Long totalIncome){
         this.totalIncome = totalIncome;
     }

     public Long getTotalIncome(){
         return totalIncome;
     }

     }
