package com.cmig.future.csportal.module.villager.good.dto;

/**Auto Generated By Hap Code Generator**/

import com.cmig.future.csportal.module.base.entity.BaseExtDTO;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import java.util.List;

@ExtensionAttribute(disable=true)
@Table(name = "csp_villager_good")
public class VillagerGood extends BaseExtDTO {
     @Id
     @GeneratedValue
      private Long id;

     @NotEmpty
      private String goodCategory;

     @NotEmpty
      private String goodSku;

     @NotEmpty
      private String goodName;

     @JsonFormat
      private String goodImage;

      private String goodSubject;

      private String goodBody;

     @NotNull
      private Long price;

     private String unit;

      private String status;

    /**
     * 商品查询关键字
     */
    @Transient
      private String keyword;

    @Transient
    private List<String> images;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setGoodCategory(String goodCategory){
         this.goodCategory = goodCategory;
     }

     public String getGoodCategory(){
         return goodCategory;
     }

     public void setGoodSku(String goodSku){
         this.goodSku = goodSku;
     }

     public String getGoodSku(){
         return goodSku;
     }

     public void setGoodName(String goodName){
         this.goodName = goodName;
     }

     public String getGoodName(){
         return goodName;
     }

     public void setGoodImage(String goodImage){
         this.goodImage = goodImage;
     }

     public String getGoodImage(){
         return goodImage;
     }

     public void setGoodSubject(String goodSubject){
         this.goodSubject = goodSubject;
     }

     public String getGoodSubject(){
         return goodSubject;
     }

     public void setGoodBody(String goodBody){
         this.goodBody = goodBody;
     }

     public String getGoodBody(){
         return goodBody;
     }

     public void setPrice(Long price){
         this.price = price;
     }

     public Long getPrice(){
         return price;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getKeyword() {
        return keyword;
    }

    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    public List<String> getImages() {
        return images;
    }

    public void setImages(List<String> images) {
        this.images = images;
    }
}
